### PR TITLE
Open Node Core links in the browser

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Adds a tooltip button when hovering Node Core frames. Clicking it opens the function definition's on Github in a new tab.

### CODE REVIEW

**Comment by mcollina** [comment]
Can you add a screenshot?

**Comment by goto-bus-stop** [comment]
Yeah, looks like:

image

Sample:

https://upload.clinicjs.org/public/52dd6a6ff82af00004d5c321f60ff578088c969590b40b064eb153ce6236a6ce/5759.clinic-flame.html

**Comment by AlanSl** [comment]
Very nice on Core frames, but on V8, Regex etc I see  a "Copy Paths" button that copies nothing to the clipboard?

**Comment by goto-bus-stop** [comment]
Huh, I could've sworn I tested that, but indeed there's a pretty obvious bug in `updateZoomBtnLabel` in this PR…

The original copy button hide code is here:

https://github.com/nearform/node-clinic-flame/blob/09b03a306c37e740170f9e43549ef020cc8e5587/visualizer/flame-graph-tooltip-container.js#L85

This patch adds:

https://github.com/nearform/node-clinic-flame/blob/09b03a306c37e740170f9e43549ef020cc8e5587/visualizer/flame-graph-tooltip-container.js#L117-L119

so it removes the `.hidden` class that was just added. Prob should move the `hideCopyButton` variable check to the same place so we just set the `.hidden` class once (and correctly)

**Comment by cuginoAle** [comment]
"Copy Paths" button [fixed here](https://github.com/nearform/node-clinic-flame/pull/29)

**Pull request merged**
