### PR TITLE
Dynamic graph cell height based on screen size

### PR DESCRIPTION
**Pull request by cuginoAle**
This PR enables the graph cell height value to change based on the screen size.
Same approach used to make the font-size dynamic.
Needs [PR on d3-fg to be merged](https://github.com/davidmarkclements/d3-fg/pull/27)

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
Dang nice :) 99% LGTM, it seems to increase the font size of the flame graph to be a bit larger than the UI text, how hard would it be to keep it about the same?

**Comment by cuginoAle** [comment]
@goto-bus-stop Done 👍

**Comment by AlanSl** [comment]
Nice, sizing looks just right. A few little things to follow up on though:

- Goes a bit wonky with browser zoom. Zoom in or out and then mouse over things, and they're redrawn in slightly the wrong place:

image

- I think we need to fix rounding and pixel grid alignment to the cell height and y values on applying them, at certain screen sizes you get a bit of heat line showing through and at others you don't, and some of the lines look a touch fuzzier than before:

image

I'll add a couple of cards for these.

**Comment by cuginoAle** [comment]
Well spotted!
I have been able to replicate the issue on Windows only though.
Can you confirm it works fine on OSX for you as well?
Will push a PR with the fix shortly...

**Comment by AlanSl** [comment]
Which issue? I'm seeing both the zoom issue and the alignment issue on Mac - it's a low PPI screen (1366 x 768) so that might be relevant

**Pull request merged**
