### PR TITLE
Feature/walkthrough

### PR DESCRIPTION
**Pull request by cuginoAle**
[depends on this [Clinic-common PR](https://github.com/nearform/node-clinic-common/pull/16)]

## Overview
This PR adds support for walkthroughs to Tools.
The walkthrough can be activated by clicking on the dedicated "how does this work" button. The walkthrough state gets stored in the URL so it is possible to share a link triggering the step-by-step guide.

## Implementation
Walkthrough steps are defined as an array of `step` objects, as per the following example:

```js
const wtSteps = [
  {
    attachTo: "#theFirstElement",
    msg:"<div>Some html content here</div>"
  },
  {
    attachTo: ".thisIsTheSecond .element",
    msg:"<div>Some other content here</div>"
  }
...
]
```

Under the hood the `walkthroughButton` depends on the `@nearform/clinic-common/base/Walkthrough` component.
Also, this component makes use of `nc-animation-pulse` to grab attention on page load.
Unfortunately there's no way to limit the animation to appear just one time.
Using the `:visited` pseudo-selector is not an option. [For privacy reasons, the styles that can be modified using this selector are very limited](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited)

## How to use it
Use the Clinic-common `walkthroughButton` button to allow users to trigger the walkthrough:

```js
const { walkthroughButton } = require('@nearform/clinic-common/base/index.js')

walkthroughButton(wtSteps, onProgress)
```
`onProgress` callback gets called whenever the user interacts with the w.t. built-in controls (prev, next, close)

## Screenshot

Screenshot 2019-03-11 at 10 28 49

## Demo page:
https://upload.clinicjs.org/public/d4544c0f9fb8a25f3b2d6ccdbeb736315fe868493e9830b13f005c0434e02666/5759.clinic-flame.html

### CODE REVIEW

**Comment by AlanSl** [comment]
I'll add some non-dummy content to this PR as suggested edits

**Comment by AlanSl** [comment]
Found a small issue while testing some content: if there's no room for a walkthrough box outside the element it's attached to, can we have the top set to a few pixels below the top of the viewport, so that instead of this:

image

...we get this (I'm also going to make the content shorter!):

image

**Comment by cuginoAle** [comment]
Thanks for noticing that @AlanSl 
I found another couple of edge cases too (one on mobile) that I should have fixed with the latest update (not pushed as yet).
I think it looks very nice now, both on desktop and mobile.
With this update the `attachTo` is optional; if absent the content will be centred to the screen.

Updated demo:
https://upload.clinicjs.org/public/01082cbbc2f10e93e0d404a04bd48ac4bed689e5cc6a92df7f3bea78d5c43676/5759.clinic-flame.html

See this screenshot on mobile:

ezgif com-video-to-gif (1)

**Comment by AlanSl** [comment]
Updated with real content: https://upload.clinicjs.org/private/b7e518a0549039121ab8ae1438e01c1a09b83cb1915b15e7176dc73c094e3639/5759.clinic-flame.html

**Pull request merged**
